### PR TITLE
PR with prow

### PR DESCRIPTION
**Pull request by crazy-john**
What I can say?

### CODE REVIEW

**Comment by crazy-john** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **crazy-john**

If they are not already assigned, you can assign the PR to them by writing `/assign @crazy-john` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=crazy-john%2Fjx-prow).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/crazy-john/jx-prow/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by crazy-john** [comment]
:star: PR built and available in a preview environment **crazy-john-jx-prow-pr-1** [here](http://jx-prow.cd-crazy-john-jx-prow-pr-1.35.237.140.13.nip.io)

**Comment by crazy-john** [comment]
/assign
This PR is urgent, so please review it ASAP

**Comment by crazy-john** [comment]
@crazy-john: you cannot LGTM your own PR.

<details>

In response to [this](https://github.com/crazy-john/jx-prow/pull/1#issuecomment-491751482):

>/lgtm


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by crazy-john** [comment]
:star: PR built and available in a preview environment **crazy-john-jx-prow-pr-1** [here](http://jx-prow.cd-crazy-john-jx-prow-pr-1.35.237.140.13.nip.io)

**Comment by crazy-john** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/crazy-john/jx-prow/pull/1#issuecomment-491800998" title="LGTM">snake-john</a>*
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **crazy-john**

If they are not already assigned, you can assign the PR to them by writing `/assign @crazy-john` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=crazy-john%2Fjx-prow).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/crazy-john/jx-prow/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by crazy-john** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/crazy-john/jx-prow/pull/1#issuecomment-491801323" title="Approved">snake-john</a>*
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **crazy-john**

If they are not already assigned, you can assign the PR to them by writing `/assign @crazy-john` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=crazy-john%2Fjx-prow).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/crazy-john/jx-prow/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by crazy-john** [comment]
New changes are detected. LGTM label has been removed.

**Comment by crazy-john** [comment]
:star: PR built and available in a preview environment **crazy-john-jx-prow-pr-1** [here](http://jx-prow.cd-crazy-john-jx-prow-pr-1.35.237.140.13.nip.io)

**Comment by snake-john** [comment]
/lgtm

very good

**Comment by crazy-john** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/crazy-john/jx-prow/pull/1#issuecomment-491805405" title="LGTM">snake-john</a>*
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **crazy-john**

If they are not already assigned, you can assign the PR to them by writing `/assign @crazy-john` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=crazy-john%2Fjx-prow).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/crazy-john/jx-prow/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by crazy-john** [comment]
New changes are detected. LGTM label has been removed.

**Comment by crazy-john** [comment]
:star: PR built and available in a preview environment **crazy-john-jx-prow-pr-1** [here](http://jx-prow.cd-crazy-john-jx-prow-pr-1.35.237.140.13.nip.io)

**Comment by crazy-john** [comment]
assign crazy-john

**Comment by crazy-john** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/crazy-john/jx-prow/pull/1#issuecomment-491807775" title="Approved">snake-john</a>*
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approvers: 

If they are not already assigned, you can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=crazy-john%2Fjx-prow).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/crazy-john/jx-prow/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
